### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hannesdelbeke** [hannesdelbeke/plugget-blender-addon#1]
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\hanne\OneDrive\Documents\repos\plugget-addon\installer\install_plugget_addon.blend\auto install Plugget Add-on", line 12, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'main.zip'
```

**Comment by hannesdelbeke** [comment]
resolved
